platform :ios, '9.0'

use_frameworks!

target 'WeiBo' do

pod 'Alamofire', '4.4'
pod 'Kingfisher', '~> 3.1.1'
pod 'AFNetworking','3.0.4'
pod 'SVProgressHUD','1.1.3'
pod 'SnapKit', '~> 4.0.0'
pod 'SDWebImage','3.7.5'
pod 'MJRefresh'
#pod 'HYLabel'



end
